Russian language changes (partOne. ru.json)
yomugames/junon pull request #32
Opened 2024-05-06 22:02 UTC by ErrorianetS

I saw some mistakes in russian words, so I want to correct them. This is the first part of update.

2024-05-19 12:47 UTC, Ruichka requested changes

2024-05-19 12:47 UTC, Ruichka commented on packages/junon-io/common/translations/ru.json
> +    "Slimy Meat Pizza": "Желейно мясная пицца",
```suggestion
    "Slimy Meat Pizza": "Желейно-мясная пицца",
```

2024-05-19 12:47 UTC, Ruichka commented on packages/junon-io/common/translations/ru.json
> +    "Drill": "Ручная дрель",
Здесь всё-таки больше подойдёт "бур".

2024-05-19 12:47 UTC, Ruichka commented on packages/junon-io/common/translations/ru.json
> +    "Refinery": "Нефтедобывающая установка",
Refinery это устаревшая постройка, перерабатывающая вещи в золото (ранее использовалась вместо торговца). С нефтью она не связана. Может быть OilRefinery?

2024-05-19 12:47 UTC, Ruichka commented on packages/junon-io/common/translations/ru.json
> +    "Generates Iron Ore": "Генерирует железную руду",
Речь идёт о буровой установке, поэтому здесь будет правильнее "Добывает".

2024-05-19 12:47 UTC, Ruichka commented on packages/junon-io/common/translations/ru.json
> +    "You just ate": "Вы уже съели",
```suggestion
    "You just ate": "Вы только что ели",
```

2024-05-19 12:47 UTC, Ruichka commented on packages/junon-io/common/translations/ru.json
> +    "Slime Broth": "Бульон из слаймака",
Слова "слаймака" не существует. Предлагаю либо "из слайма", либо "из слизи".

2024-05-19 12:47 UTC, Ruichka commented on packages/junon-io/common/translations/ru.json
> +    "Starting": "Стартуем",
По контексту происходит загрузка сектора.

2024-05-19 13:21 UTC, ErrorianetS commented on packages/junon-io/common/translations/ru.json
> +    "Slimy Meat Pizza": "Желейно мясная пицца",
А зачем исправлять первую часть, когда уже есть третья?

2024-05-20 15:02 UTC, Ruichka commented on packages/junon-io/common/translations/ru.json
> +    "Slimy Meat Pizza": "Желейно мясная пицца",
> А зачем исправлять первую часть, когда уже есть третья?

А зачем делать второй PR чтобы исправить ошибки первого?

2025-09-01 15:57 UTC, closed without merging