added  $index function
yomugames/junon pull request #34
Opened 2024-07-16 11:43 UTC by notjc821

(math is cool)

2024-07-28 02:27 UTC, notjc821 commented
Can someone help me fix /level command? Its health and damage upgrades are not working correctly. I tried to fix it but failed...

2024-07-28 02:39 UTC, notjc821 commented
Can someone help me add an "owner" attribute to /projectile? I tried to add and test it, but the test results were not entirely successful...

2025-07-14 18:54 UTC, simpleyuji requested changes
most of the functions not working like abs, log, max since they're not in functiontable

2025-07-14 18:54 UTC, simpleyuji commented on packages/junon-io/server/entities/event_handler.js
>        "$getPlatformByCoords": true,
root, abs, log, min, max, abs, floor, ceil is missing here. they need to be in getFunctionTable. otherwise, it wont work

2025-07-14 18:54 UTC, simpleyuji commented on packages/junon-io/client/main.ejs
> -                            <td class='function_name'>$modulo</td>
why are we removing $modulo function? i think it should stay in the codebase

2025-07-14 18:54 UTC, simpleyuji commented on packages/junon-io/server/entities/event_handler.js
> +  isGetEffect(entityId, effectName) {
a better name for this is `hasEffect`

2025-07-15 02:10 UTC, notjc821 commented on packages/junon-io/server/entities/event_handler.js
>        "$getPlatformByCoords": true,
Sorry, I remember coding them, but somehow I deleted them. Perhaps I didn’t copy them over after testing when I was preparing to contribute😅

2025-07-15 02:22 UTC, notjc821 commented
I have fixed the problems

2025-07-15 02:25 UTC, notjc821 commented on packages/junon-io/client/main.ejs
> -                            <td class='function_name'>$modulo</td>
Sorry, I accidentally deleted it😅

2025-07-15 02:25 UTC, notjc821 commented on packages/junon-io/server/entities/event_handler.js
> +  isGetEffect(entityId, effectName) {
ok

2025-07-15 02:50 UTC, notjc821 commented
btw, simpleyuji, i wanna add "raid:true/flase" in /spawnmob,
Ex. "/spawnmob guard 1 10 12 raid:true" and it will spawn a mob with raid behavior.
do you know how to do it?(I have tryed this for several times, but I all failed...)
Or could I ask you to help me solve this problem,please?
also, can you fix the bug that some mobs(ex: guards, sappers, trooper) cannot damage walls(lamp, bed cannot be damaged by them too)?
I really need your help and I hope you can help me solve this problem🛐

2025-07-15 19:52 UTC, merged